name: Theme preview

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - theme-preview-script
      - "themes/index.js"
  issue_comment:
    types: [edited]

jobs:
  comment:
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        if: contains(github.event.comment.body, 'Automated Theme Preview')
        run: |
          echo say hello
  build:
    runs-on: ubuntu-latest
    name: Install & Preview
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - run: npm run preview-theme
        env:
          CI: true
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
